#!/bin/bash

gcc main.c 

for file in  *.txt
    do
        echo "Processing file : $file ... "
        ./main $file
        echo "$file finished processing..."
        echo "Elapsed time : "
        ps -ef | grep "main INPUT" | awk 'NR==1 { print $7 }'
        echo "Saving results... "
        cat output.out >> results
        echo "The results are currently : "
        cat results
done


